### ISSUE TITLE
Nodes and transform problems.

### ISSUE THREAD

**Issue by almette01** [BadDogSkyrim/PyNifly#100]
Hello,
firstly, thank you for this add-on, because this one is at least somehow working and someone is working on it(I have tried bunch of them and always there were some problems). But here are some problems too.
1. Some nodes are not importing correctly(aren't parented)
Here how it looks like after import:
![image](https://user-images.githubusercontent.com/104219055/164755950-730ec379-725e-4bf4-b310-fe448c855437.png)
And here is how it suppose to looks like(I guess...) in NifSkope:
![image](https://user-images.githubusercontent.com/104219055/164756205-ed2f66bc-d9ce-4589-a334-89bd209d8560.png)
The "BSFaceGenNiNodeSkinned" should be inside "Object" and the meshes should be inside "BSFaceGenNiNodeSkinned". If I fix that manually, it is working fine.
2. The transforms seems to be not correct, because when I import head to **Skyrim SE** using **RaceMenu** the eyes and teeth are in correct place but head and other things are very high above neck.
3. The order of nodes is not the same as before edit in blender, but it seems like it is not big problem.

Keep in mind that all I am saying is just guessing, because I am not experienced in this kind of stuff, so I am sorry if I am wrong.

**Comment by BadDogSkyrim** [comment]
If you want to send me the nif, I'll have a look. I do have some nifs in the test suite that group shapes under a common node like that, but they are not skinned, so maybe that's the difference.
