### ISSUE TITLE
Exporting vertex alpha data

### ISSUE THREAD

**Issue by JonnyWang33** [BadDogSkyrim/PyNifly#102]
Hello, this is likely user error so I apologize, but using vertex paint to add alpha and then exporting does not seem to carry the changes over. I am trying to animate grass.

Thank you for your time!

**Comment by mindflvx** [comment]
Do you have the vertex color layers set like this?

![image](https://user-images.githubusercontent.com/7015533/166104480-84f72be9-d765-4f51-8cca-287bea7da2fb.png)

**Comment by JonnyWang33** [comment]
Thank you so much! This was super helpful and fixed my issue : )
