### ISSUE TITLE
Some bones missing when importing Zex skeleton

### ISSUE THREAD

**Issue by dagobaking** [BadDogSkyrim/PyNifly#105]
First, thank you for this great add-on! Along with the newly available FBXImporter tool (https://www.nexusmods.com/fallout4/mods/59849), this makes an animation workflow possible that doesn't require 3DSMax.

I'm having a problem with importing the popular Zex skeleton ( https://discord.com/channels/499328900371972097/542868396388122654 ).

Some of the bones needed to complete HKX creation (see the example .blend from the FBXImporter tool above to see what bones are needed) don't appear in the imported armature. Specifically, various Weapon bones are missing ( "WeaponExtra1", "WeaponExtra2", etc). But, I'm not sure if those are the only ones.

Is this an issue with PyNifly? Or, am I missing a step to get those bones from somewhere else? Or, is there perhaps something about the Zex skeleton that needs to be fixed?

**Comment by BadDogSkyrim** [comment]
Could be my issue or not. For this you should turn off the "create bones" option on import (because the skeleton has all the bones). I'll check it out.

**Comment by dagobaking** [comment]
I did some more digging and found out that the bones I need are in skeleton.hkx rather than skeleton.nif. Now I'm just trying to figure out how to get those into Blender...

**Comment by BadDogSkyrim** [comment]
I don't know. I'm starting to look at animations now, but the hkx files are a black box.

**Comment by dagobaking** [comment]
You can turn those into XML with this: https://github.com/Dexesttp/hkxpack

The animation ones are probably more complex. But, skeleton.hkx is surprisingly simple in XML form. I think it's basically just config for what animation bone data to look for, various constraints, etc.
