### ISSUE TITLE
Fo4: export fail

### ISSUE THREAD

**Issue by thomasandersen** [BadDogSkyrim/PyNifly#109]
Hi 
I get an export failed error on this blend/object (please see attached vanilla Windows zipped blend file)

Using: 
Blender 3.0.0/Windows, 
PyNifly 5.3.0

Steps to reproduce
1. Open the blend file
2. Select object at center of the scene
3. Choose file > Nif file with Nifly
4. Export with Fallout4 as target

Result: File is not created/exported. Error log says: "Export of nif failed, see console window for details"
Expected result: Nif file created/exported

Edit: updated step 4/target. I have tried other Skyrim and Skyrim SE and get the same error

[export_error1.zip](https://github.com/BadDogSkyrim/PyNifly/files/8717337/export_error1.zip)

**Comment by BadDogSkyrim** [comment]
Yeah, okay, and did you look at the console window and see what the problem was?

**Comment by thomasandersen** [comment]
Sorry. I was not aware of Blender's conosle window and looked in the Info Window

`AttributeError: 'NoneType' object has no attribute 'data'`

The traceback

```
Traceback (most recent call last):
  File "addons\io_scene_nifly\__init__.py", line 3135, in execute
    exporter.export(context.selected_objects)
  File "addons\io_scene_nifly\__init__.py", line 3033, in export
    self.execute()
  File "addons\io_scene_nifly\__init__.py", line 3028, in execute
    self.export_file_set(None, '')
  File "addons\io_scene_nifly\__init__.py", line 2988, in export_file_set
    self.export_shape(obj, sk, arma)
  File "addons\io_scene_nifly\__init__.py", line 2853, in export_shape
    self.extract_mesh_data(obj, arma, target_key)
  File "addons\io_scene_nifly\__init__.py", line 2526, in extract_mesh_data
    uvlayer = editmesh.uv_layers.active.data
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by thomasandersen** [comment]
I am lazy ;) 
There were no UV's for the object
Problem solved

**Comment by BadDogSkyrim** [comment]
I'll see about better error checking.
