### ISSUE TITLE
Environment map scale gets automatically set to 1.0 when exporting

### ISSUE THREAD

**Issue by JonnyWang33** [BadDogSkyrim/PyNifly#110]
I discovered this bug when importing "sufficiently optimized snow berries" which has the Environment_Mapping flag active (BSLightingShaderProperty > Shader Flags 1 > Environment_Mapping) and an Environment Map Scale of 0.0.

After exporting, the environment map scale was set to 1.0.

**Comment by BadDogSkyrim** [comment]
WTF does a scale of 0 even mean? And how did it look after exporting?

Regardless, it goes on the bug list.

**Comment by JonnyWang33** [comment]
A scale of 0 essentially disables the shader. I'm not sure why WankingSkeever didn't just disable the shader flag, but regardless, it took me a very long time to figure it out. Thank you! The plugin has been working great otherwise and I've been busting out plants at a great pace (except these berries have been hugely problematic).

[https://imgur.com/0dcf4fcd-b547-4c0e-acb1-846a9534457b](https://imgur.com/0dcf4fcd-b547-4c0e-acb1-846a9534457b)

**Comment by speaker-60** [comment]
Just went to report this and saw it was already mentioned its the same with fallout 4
![image](https://user-images.githubusercontent.com/14035515/183142930-7cb96262-f42d-4336-96e3-d6a43b929d9e.png)

**Comment by BadDogSkyrim** [comment]
Fixed in next release
