### ISSUE TITLE
Fallout 76 Nif support?

### ISSUE THREAD

**Issue by bizzclaw** [BadDogSkyrim/PyNifly#111]
I just want to say this tool is a godsend. Thank you so much! 

This works **perfectly** for Fallout 4 nifs, which is amazing enough, but I have to ask... How much work would it require for this to support importing nifs from Fallout 76? Being able to make modifications to them would make it possible to do some really cool stuff for Local fallout 76 mods, and in case we ever get more modding tools in the future, it would be helpful. Not a huge deal, of course, but I figured I might as well ask. Thank you!

**Comment by BadDogSkyrim** [comment]
The layer I've built on, Nifly, doesn't support FO76 completely, so it's a good bit more work. Plus I don't have the game or mod for it so testing would be a problem. I'm more inclined to address MOPP collisions and animations in the games that are supported first.

**Comment by bizzclaw** [comment]
Thank you for giving a reply on this at least. I appreciate that much.

Actually, not going to lie. I'd be much more interested in getting HKX animations working. I have a friend who got them working for Max, but I much prefer doing all of my work in blender. Here's the link to their tool if you'd like to have a look.

https://github.com/PredatorCZ/HavokMax

Again, thank you for at least doing this much! I look forward to what you create in the future.

**Comment by SK83RJOSH** [comment]
Just an FYI, I did some hacking over the last couple of days to get this working, the code isn't available yet (https://github.com/ousnius/nifly/pull/37) but this is definitely possible now:

https://user-images.githubusercontent.com/1371787/186948615-a44f02d5-f132-471e-a5f7-90fc782c1ac7.mp4


https://user-images.githubusercontent.com/1371787/186948977-b0bc2e89-6d9b-4e6b-8468-8547af60b2ab.mp4

**Comment by bizzclaw** [comment]
> Just an FYI, I did some hacking over the last couple of days to get this working, the code isn't available yet ([ousnius/nifly#37](https://github.com/ousnius/nifly/pull/37)) but this is definitely possible now:
> 
>  blender_54tnEj9ecl.mp4 
>  blender_89m3kwBlBs.mp4

You are a god. Please let me know if you submit this somewhere or at least how you got this working!

**Comment by SK83RJOSH** [comment]
> > Just an FYI, I did some hacking over the last couple of days to get this working, the code isn't available yet ([ousnius/nifly#37](https://github.com/ousnius/nifly/pull/37)) but this is definitely possible now:
> > blender_54tnEj9ecl.mp4
> > blender_89m3kwBlBs.mp4
> 
> You are a god. Please let me know if you submit this somewhere or at least how you got this working!

You're too kind, but really, I just wanted to be able to get at the skinned models myself... 😄

Here's a [WIP](https://github.com/BadDogSkyrim/PyNifly/files/9436001/io_scene_nifly.zip) version you can play around with. It supports import and export just fine, but the materials can appear a bit broken in blender. That's because I didn't do any work to use the correct BSDF setup (everything since FO4 should use Specular BSDF) but it should work just fine for most things.
