### ISSUE TITLE
Missing DLL while using PyNifly in Windows 7

### ISSUE THREAD

**Issue by TerryOppsi** [BadDogSkyrim/PyNifly#115]
I downloaded a version of blender 3 for windows 7 from here https://github.com/nalexandru/BlenderCompat/releases/tag/3.0.0

I also downloaded the latest version of PyNifly

After installing the add on it doesn't appear in the add on list. So i manually move the files from the zip into the blender addons folder it shows up in blender then i click to enable it but i get an error message in the system console when starting up blender saying "Error pynifly DLL not found" and a different message when I try to import a NIF saying "could not find module NiflyDLL.Dll". 

Is there anyway to fix this, I've been trying all day, I've tried different versions of blender even the earlier ones that work with windows 7, I have also tried moving the files around to help blender detect them. Maybe there is a version of PyNifly that works with windows 7, it seems to be looking for DLL files that come with windows 8, but I would have thought the Blender 3 for windows 7 would generate them, but i don't knwo much about this sort of thing so i could be completely wrong?  Please help.

![image](https://user-images.githubusercontent.com/107322044/173202166-b3d4a1b1-2791-4571-a6a8-b534ea5194bb.png)

**Comment by BadDogSkyrim** [comment]
Probably your manual install is screwed up somehow.

Did you get the zip from the Releases page? Did you enable the plugin after installing it? Did you restart blender?

**Comment by TerryOppsi** [comment]
I got PyNifly from here "https://github.com/BadDogSkyrim/PyNifly" I clicked code then download zip

I wasn't able to enable the plugin in the traditional way, in blender going from preferences-addons-installs and locating the zip then installing it, it didn't show up in the list.  

I restarted blender at least 20 times while trying to get it to work

**Comment by TerryOppsi** [comment]
I hear that Python 3.9+ is not supported on Windows 7, does PyNifly only work on windows 8? If so that might be the problem.

**Comment by BadDogSkyrim** [comment]
What is this "Pynifly-main.zip" of which you speak? You should be downloading "io_scene_nifly.zip" from the release page.

**Comment by BadDogSkyrim** [comment]
Not a clue.

I *think* GitHub lets you download a whole project as a zip file, so you're getting source code and test files and everything. Go to "Releases", that's what you want.

**Comment by TerryOppsi** [comment]
Okay. Thank you BadDog, you saved me.
