### ISSUE TITLE
Mesh splits in-half on export?

### ISSUE THREAD

**Issue by JustTooSweet** [BadDogSkyrim/PyNifly#118]
I'm not _completely_ sure if this is a bug or intentional but whenever I export the head mesh I'm working on it gets split down the middle which obviously makes duplicate vertices and makes shape keys slightly problematic in some areas, especially since they can't be mirrored when this happens
(it is split perfectly down the middle on x-axis) 

on export:
the vert count increases by 200+, removing the duplicate vertices and exporting again just causes the problem to repeat itself

**Comment by BadDogSkyrim** [comment]
Shape keys should work, I hope, because they're made after the split. The tri file should always match whatever was exported.

Check your UV and face orientation. I'm guessing you worked on a half-head and mirrored. That will cause a seam if the faces on either side of the centerline either have different UV coordinates or (maybe) have different face orientations.

**Comment by JustTooSweet** [comment]
it pretty much happens regardless of what I do so I'll just consider it a limitation, I can still make shape keys but mirroring them is a bit inconvenient, but as another possible request, could you add the ability to export shape keys with non vanilla names for fallout 4? I just find it inconvenient that I have to rename them just to export them is all

**Comment by BadDogSkyrim** [comment]
If you send me the head mesh I'll have a look and tell you what's going on. 

In a minute I'll post my cheat sheet for how I make a head. Mirroring the shape keys happens for (almost) free.

Say more about why you need non-vanilla names in FO4. Expressions are run by the engine so you don't need it for them. (Tell me if I'm wrong.) Other shape keys do get exported to the chargen file.

**Comment by BadDogSkyrim** [comment]
Turns out I wrote up the process already: https://github.com/BadDogSkyrim/PyNifly/wiki/Modding-Process:-Making-a-Head

**Comment by JustTooSweet** [comment]
non vanilla shape keys can be added and used by the race record for chargen purposes, I'm specifically using them for a custom race, but I've had to export them with vanilla names and use outfit studio to rename the shape keys and export again

I'll also be sure to check your guide out as it may prove helpful for me, so thanks for that

Here is the head mesh as-well, you'll have to excuse the bad normals, it seems to mess those up too even when I try to fix them
https://www.mediafire.com/file/9nzyby98dvcvtyw/Head.nif/file

**Comment by BadDogSkyrim** [comment]
The blender file will be more helpful.

Any shape key that is not recognized as an expression (and doesn't have a "*" or ">" in front) is exported to the chargen tri file.

**Comment by BadDogSkyrim** [comment]
Had a look. As I said upthread, UV can cause a seam to be split. In your case, the centerline verts are in different places on the UV, left side vs. right side.
