### ISSUE TITLE
Plugin only imports 30 Bstrishapes

### ISSUE THREAD

**Issue by gururaj20000** [BadDogSkyrim/PyNifly#120]
I have noticed that blender only imports 30 meshes if the nif contains more than 30 BSTriShapes/BSSubIndexTriShapes. 

Blender 3.1.2
Pynifly 5.8.2

**Comment by BadDogSkyrim** [comment]
OMG

Do you have a nif handy with more than 30?

**Comment by gururaj20000** [comment]
Hello! yes i happen to have a mesh with more than 30 bstrishapes.
[Outfit.zip](https://github.com/BadDogSkyrim/PyNifly/files/9348189/Outfit.zip)
I am trying to optimise these meshes in blender by merging a lot of the bstrishapes since they use the same bgsm file.

**Comment by BadDogSkyrim** [comment]
Holy shit.

... Okay. Do you know why some shapes are BSTriShape instead of BSSubIndexTriShape?

**Comment by gururaj20000** [comment]
Yeah the bstrishapes inbetween is something i fixed with outfit studio. But i faced the issue with a nif solely containing BSSubIndexTriShape. 

Here's the fixed nif.
[Outfit_fixed.zip](https://github.com/BadDogSkyrim/PyNifly/files/9350848/Outfit_fixed.zip)


I had issues with only the first 30 BSSubIndexTriShapes getting imported into blender with this nif as well.

**Comment by BadDogSkyrim** [comment]
Yeah, apparently I limited shapes to 30 as a quick way to get things working and never fixed it. Fixed in next release.

**Comment by gururaj20000** [comment]
Thanks!
