### ISSUE TITLE
Exporting childless nodes to get positional data for weapon attachments and bone remapping

### ISSUE THREAD

**Issue by AlecRFreeman** [BadDogSkyrim/PyNifly#127]
Currently the importer/exporter seems to ignore nodes with no child data (such as mesh data), which is useful normally but causes issues when exporting nodes like ProjectileNode which determine the position of the spawned muzzle flash for weapons, and are also used for remapping bone positions for assembly poses. Since these nodes aren't exported, they need to be added manually in Nifskope to ensure functionality. I can provide examples if needed!

I've found a current workaround of attaching a blank mesh and deleting it in Nifskope afterwards.

**Comment by BadDogSkyrim** [comment]
Pretty sure this is fixed in the latest.
