### ISSUE TITLE
Blender 3.3 crashes when editing bethesda _go mesh

### ISSUE THREAD

**Issue by HeinrichGuil** [BadDogSkyrim/PyNifly#129]
If I try to remove vertices or invert normals blender crashes. Here is the [mesh ](https://drive.google.com/file/d/1FlG3ej09aDEuU_ifuAHwG9XbfWAPrmT4/view?usp=sharing)

**Comment by BadDogSkyrim** [comment]
Wow, so it does. A number of the operations that work on all the verts in the mesh fail. Huh.

**Comment by BadDogSkyrim** [comment]
Fixed in 5.22.
