### ISSUE TITLE
Export: set transform/scale 

### ISSUE THREAD

**Issue by thomasandersen** [BadDogSkyrim/PyNifly#130]
It would have been nice to set a transform scale when exporting a nif

My Blender objects are usually in a 1/10 scale in the scene and I export the object using obj as the transform format with a preset where the scale is set to 10 in Blender's default obj export UI. 
The obj is then imported from 3dMax for final gif export etc. 
I guess this is a common workflow for those who use obj. 

My coding skills are rust and I am not super familiar with Blender add-on/development, but I guess I could try look into this if it is something worth doing.

Let me know if this was unclear

Thanks

**Comment by BadDogSkyrim** [comment]
Doing it's not hard. Doing it in a way that's logical and works with what people are trying to do is more difficult. Mostly I haven't been applying transforms, except to export the transform itself when that makes sense. 

I've never really understood the 1/10 scale thing. If the nif expects a certain scale, why are we scaling down and then scaling up again on export (or vice versa, whichever it is).

**Comment by thomasandersen** [comment]
It has been a while and AFK, but I think it is the default obj exporters/importers in Blender and Max 2013 that deals with scale differently.
E.g. The default obj importer in Max scales objects in an obj file up 10 times. 
Similar thing happens when using FBX.  
You then have to manually scale it down 10 times, apply an X-form modifier (apply transforms) then apply the modifier. 
It is a bit cumbersome.

I have a lot of existing work that follows this flow :) and it seems like you have seen this before :)

I think it is one of the reasons Blender has this in the obj and fbx exporters

![blender-obj-export-ui](https://user-images.githubusercontent.com/194093/204063720-5e82213a-01bf-40b2-a71f-19257009e3d5.png)

**Comment by BadDogSkyrim** [comment]
I suppose I could do like that and have a magic scale on the export. I haven't needed it because as long as you're importing and exporting through PyNifly it all just works. And anything else, you can scale it up in Blender and then it's fine from that point forward. Is there a need too keep importing from other tools?

(Just looking to understand the workflow, not looking for reasons not to do it. :-) )

**Comment by HeinrichGuil** [comment]
Most of modifiers are by default set to real scale. I.e. 1.8m for human and everything scaled accordingly. It's just a nice equality of life feature.
(but complex collisions would be even more so)

**Comment by BadDogSkyrim** [comment]
Okay, that's something I never knew.

I'm not sure I'm seeing this in Skyrim/FO4 files. Height of the female body is 102.6, without scaling, so that's 10.26 with, which is kinda large for a girl. 

Also is there any concern about losing precision? I have some scripts that round to 4 decimal places on the ground that that's all that matters.

**Comment by thomasandersen** [comment]
> I suppose I could do like that and have a magic scale on the export. I haven't needed it because as long as you're importing and exporting through PyNifly it all just works. And anything else, you can scale it up in Blender and then it's fine from that point forward. Is there a need too keep importing from other tools?
> 
> (Just looking to understand the workflow, not looking for reasons not to do it. :-) )

I am sure if we talk through ober each other here, but the transform/scale should is most cases kept at 1.0

An outline of my workflow for creating a nif is:

1. Create 3d object in Blender
2. Export to OBJ from Blender
3. Import the .obj in MAX
4. Export to nif from MAX
5. Process the nif with Elric tool.

There are some extra steps in between import and export from MAX like applying BGS(X) materials, adding collisions etc., but it is not relevant here, I think. 
Also the Elric step step is not relevant. 

Let's say I have standard cube with transform scale set to 1.0 in Blender and I follow the workflow above, the final result nif ends up visually 10 times larger than what I intended.
The reason is a difference in how the default OBJ importeres/exporters in Blender and MAX treats transform scale, or something like that.
Instead of manually scele things in Blender and MAX I use the transform arguement in Blender's default exporter.
Why the two softwares treats scale differently, I do not know to be honest, but I think this is one of the reasons why Blender's obj/fbx exporters have a transform/scale argument. I have seen old discussions about this before.
If I open an existing Blender project and use PyNifly for exporting I have to manually transform/scale my object up 10 times first.

I am not sure if this helps for understanding the reasoning behind the suggestion. Let me know and I can try to explain it more. 
Again, I am talking about the transform scale, not the measurment/unit side of things

**Comment by BadDogSkyrim** [comment]
No, I understand the issue. I just have to figure out how to lock it in. 

I'mma do an update within the next week I think and I'll try to get this in.

**Comment by BadDogSkyrim** [comment]
Fixed in next release.
