### ISSUE TITLE
Export failing when node hiearchy has multiple NiNodes

### ISSUE THREAD

**Issue by VISaberToothIV** [BadDogSkyrim/PyNifly#134]
Example (FO4): Meshes\Pipboy\CharacterAssets\Pipboy.nif

The Fallout 4 Pipboy can be imported correctly with appropriate node hierarchy, but on export it fails with this error:

![blender_7Q8CVc0xRP](https://user-images.githubusercontent.com/27841614/212522184-1cd84361-7200-4398-bcb8-72e02e28ad56.png)

Through experimentation I have found that this happens only when multiple NiNodes are in a hierarchy above a mesh object. I have tested a couple of different Nif files including the Minigun as a second example and it also fails to export, but will import just fine.

**Comment by BadDogSkyrim** [comment]
Fixed in next release.
