### ISSUE TITLE
Fails to export BSLeafAnimNode

### ISSUE THREAD

**Issue by JonnyWang33** [BadDogSkyrim/PyNifly#135]
Fails to either import or export in the proper format.

**Comment by BadDogSkyrim** [comment]
Do you have a nif that uses this node?

**Comment by JonnyWang33** [comment]
All animated plants use this node. It would also be amazing if switch node architecture could be preserved as well.

[https://www.nexusmods.com/skyrimspecialedition/mods/81284?tab=files](https://www.nexusmods.com/skyrimspecialedition/mods/81284?tab=files)

**Comment by BadDogSkyrim** [comment]
Fixed in next release.

**Comment by JonnyWang33** [comment]
YOU ARE THE ABSOLUTE BEST THANK YOU!!!!!!!!!
