### ISSUE TITLE
Scale Correction does not change the size of mesh

### ISSUE THREAD

**Issue by VISaberToothIV** [BadDogSkyrim/PyNifly#136]
Scale Correction does not seem to change the size of imported meshes in the viewport or exported meshes in the Nif file. It does not appear to affect the object scale value in Blender or Nifskope either. I have tried several types of Fallout 4 meshes and they all seem to be unaffected by it.

**Comment by BadDogSkyrim** [comment]
I have tests that say it's working but maybe there's something wrong with them. I'll check.

**Comment by VISaberToothIV** [comment]
![blender_1boMkJ1Zo2](https://user-images.githubusercontent.com/27841614/217239337-5f433a53-2b3f-4cad-82e7-62da981932f5.png)
![blender_qeubip2B6J](https://user-images.githubusercontent.com/27841614/217239343-07775b77-58f6-4129-a721-db1b79f48b94.png)

**Comment by BadDogSkyrim** [comment]
Still not seeing the problem, closing the issue. Raise it again if it's real.
