### ISSUE TITLE
PyNifly Blender .nif Import via script

### ISSUE THREAD

**Issue by AR-128** [BadDogSkyrim/PyNifly#137]
I have a question, I asked about on a couple of forums already. I never got much help and don't understand enough about python to figure it out on my own. I want to batch process nif files, using PyNifly addon, I would like to import a .nif through a script without going through the menu manually. any help would be much appreciated.

my script
```
import bpy
bpy.ops.import_scene.pynifly(filepath="E:/Meshes/10mmAmmo.nif")
```
system console
```
====================================
PYNIFLY IMPORT NIF V8.2.0


ERROR:pynifly:Import of nif failed
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender 3.0\3.0\scripts\addons\io_scene_nifly\__init__.py", line 1963, in execute
    NifImporter.do_import(fullfiles, flags)
  File "C:\Program Files\Blender Foundation\blender 3.0\3.0\scripts\addons\io_scene_nifly\__init__.py", line 1882, in do_import
    imp = NifImporter(filename, flags, chargen=chargen, scale=scale)
  File "C:\Program Files\Blender Foundation\blender 3.0\3.0\scripts\addons\io_scene_nifly\__init__.py", line 790, in __init__
    self.filename = filename[0]
IndexError: list index out of range
INFO:pynifly:

PyNifly IMPORT of [] completed WITH ERRORS {'CANCELLED'}
====================================


Error: Import of nif failed, see console window for details
Traceback (most recent call last):
  File "\Text", line 2, in <module>
  File "C:\Program Files\Blender Foundation\blender 3.0\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Import of nif failed, see console window for details

Error: Python script failed, check the message in the system console
```
I installed an addon called ActionRecorder and got this information, about importing
script
`bpy.ops.import_scene.pynifly(filepath='', filter_glob='*.nif', files=<bpy_collection[0], IMPORT_SCENE_OT_pynifly.files>, create_bones=True, scale_factor=1.0, rename_bones=True, rename_bones_niftools=False, import_shapes=True, apply_skinning=True)`
console error
`Error: invalid syntax (<string>, line 1)`

**Comment by BadDogSkyrim** [comment]
Truth is, I'm dumber than I ought to be about large parts of Blender scripting and I don't know what bpy.ops.import_scene.pynifly will do. I think there's an easier way tho.

If you have a look at the pynifly_tests.py file--if it's not shipped it's on the github--you'll see a ton of tests showing how to invoke PyNifly from a Blender script (because that's all the tests are, really). You'll have to figure out how to get the right context but that shouldn't be too hard--you'll have to invoke the main file but convince it not to install itself. 

If you just want to hack the files and don't actually need Blender, it's even easier. pynifly.py can be invoked from any python program. At the end of that file are a ton of tests that show you how to use it.

**Comment by AR-128** [comment]
Thanks for your input BadDogSkyrim my main goal is to batch convert to fbx every fallout 4 nif, I'll have a look tomorrow not holding my breath though. My knowledge of python and blender is limited. bpy.ops.import_scene.pynifly(filepath="E:/Meshes/10mmAmmo.nif") should call an importer and use the path in the brackets I think.

**Comment by AR-128** [comment]
I'm really having a difficult time, I'm not sure what parts of pynifly_tests.py I need to use to invoke __init__.py

**Comment by BadDogSkyrim** [comment]
I just meant you could look at it and copy the calls it uses.

But re-reading the OP, maybe this is simpler than I thought. Try using filepath=["E:/Meshes/10mmAmmo.nif"]

It's quite possible it expects a list, not a string.

**Comment by AR-128** [comment]
I tried it but gives me an error, I wish could help myself but it's too complex for me to understand.

bpy.ops.import_scene.pynifly(filepath=["E:/Meshes/Ammo/10mm/10mmAmmo.nif"])

TypeError: Converting py args to operator properties:  IMPORT_SCENE_OT_pynifly.filepath expected a string type, not list

**Comment by BadDogSkyrim** [comment]
Okay, so maybe it does want a string. But that gave you an error too. I'll have a look.

**Comment by AR-128** [comment]
Thanks I appreciate it

**Comment by 6ooflames** [comment]
This worked with versions up to 5.16 which didn't have the capability of importing multiple files.
Looking at __init__.py, it seems the files=<> is the culprit.

**Comment by podvornyakva** [comment]
> This worked with versions up to 5.16 which didn't have the capability of importing multiple files. Looking at **init**.py, it seems the files=<> is the culprit.

Why? 8.2 on github and 8.4 on nexus already.

**Comment by AR-128** [comment]
@6ooflames Really I opened init.py v8.2 I can't find files=<> anywhere, what would I need to change to make it work? Thankyou

**Comment by 6ooflames** [comment]
The easiest way to make it work is to just use a version before the update which introduced that extra object. You could ofc compare the NifImporter class from previous versions with the current one, and see what changed to make the file list come up empty even if you specify a filepath="" string.

**Comment by BadDogSkyrim** [comment]
Thanks for digging.

**Comment by 6ooflames** [comment]
There's a script on my GitHub which utilizes this Importer to import entire CELLs using a refutable and an objdata table. It too was broken because of the change from filepath="" to files=<>

**Comment by 6ooflames** [comment]
There's a script on my GitHub which utilizes this Importer to import entire CELLs using a refutable and an objdata table. It too was broken because of the change from filepath="" to files=<>

**Comment by BadDogSkyrim** [comment]
I think the problem here is that I was looking at the "files" list but not handling it reasonably if that list wasn't there but the "filepath" property was. I've put in checks for that but I can't test it because the script in the OP doesn't work for me, not even if I load up an old version prior to the change. So when the next rev (post 9.0) goes up have a look and see if it's better.

**Comment by BadDogSkyrim** [comment]
I take that back. I can make the scriptlet work, dunno why it didn't before. This seems to be working. I'll get an update posted soon.

**Comment by BadDogSkyrim** [comment]
Fixed in latest.
