### ISSUE TITLE
No option to export .tri file

### ISSUE THREAD

**Issue by Snowstar38** [BadDogSkyrim/PyNifly#152]
I'm not sure if this is intended, but I can import .TRI files... can't export them, though.

**Comment by BadDogSkyrim** [comment]
It's intended.

I spent literal years doing races for Skyrim and dealing with tris was always a freaking nightmare. So pyNifly does it for you--if you export a mesh with shape keys (named appropriately) you'll get tris for free. Details are in the wiki.
