### ISSUE TITLE
Vertex Colors not exported for multiple objects

### ISSUE THREAD

**Issue by Lance2047** [BadDogSkyrim/PyNifly#157]
Hello,

great & straightforward tool! Only that I don't seem to be able to correctly export (RGB) Vertex Colors for multiple objects.
When I export them individually the vertex colors are correctly transferred. Is that my fault due to 
missing configuration, or is multi-object Vertex Colors export not supported?

Using Blender Version: 3.3.1 with the newest version of your plugin

Steps:
- model any mesh + add some vertex colors
- duplicate that mesh
- export both meshes as a single nif

![sample](https://github.com/BadDogSkyrim/PyNifly/assets/87235870/ae4d2ac7-532d-41ed-96ff-6d9bcf8ed66c)

**Comment by BadDogSkyrim** [comment]
OK, that's wierd. Will check it out.

**Comment by Lance2047** [comment]
Did some further testing and multi-object Vertex Colors are only then not exported,
when the name is not "unique" e.g., object "Cube" is duplicated or split -> duplicate Cube is named: "Cube.001".

Apparently is gets confused, when Blender adds the increment suffix to the object name.
So as a workaround giving each object a truly unique name fixes it.

**Comment by BadDogSkyrim** [comment]
OK, thanks, helpful. Still no idea why that's a problem.

I have the whole DLL spread out across the floor in parts. When I get it back together I'll have a look.

**Comment by BadDogSkyrim** [comment]
Fixed in upcoming release.
