### ISSUE TITLE
V10.x compatibility regression

### ISSUE THREAD

**Issue by LD-531** [BadDogSkyrim/PyNifly#159]
Some meshs converted with NIF Optimizer cannot be import.

Blender 3.6.0 @ W10/W7, tried:
V10.5 - failed
V10 - failed
V9.10 - OK
V8.5 - OK
[Sample_NIF_SkyrimSE.zip](https://github.com/BadDogSkyrim/PyNifly/files/12165855/Sample_NIF_SkyrimSE.zip)

**Comment by BadDogSkyrim** [comment]
Fixed in current release.
