### ISSUE TITLE
An easy way to revert to the pre-10.0 bone rotation would be nice. It was significantly more compatible with external animation software.

### ISSUE THREAD

**Issue by Akira13641** [BadDogSkyrim/PyNifly#167]
With 9.10 and earlier, I was able to import **any** Skyrim character mesh (along with the particular skeleton NIF that corresponded to it) to Blender, change nothing, immediately re-export at 0.01 scale to FBX and then rig / animate that FBX file in Cascadeur, for example. Afterwards I'd just re-import the FBX back into Blender, and export out to both LE and SE Havok animation files using the [Blender HKX plugin.](https://github.com/jgernandt/blender-hkx)

I don't know enough about much of anything to understand what the intended purpose of the changes in 10.0+ are, all I know is that it's just all wrong upon re-import to Blender from Cascadeur, resulting in exported HKX files that are massively distorted and not even slightly correct in-game.

**Comment by BadDogSkyrim** [comment]
TBH when I made the change I wasn't sure anyone was actually using that route to get animations out, and I didn't know about that tool. I was implementing animations myself, but if this tool is working I might abandon that route altogether. 

Why do you need the FBX -> Cascadeur step? Is it just a better animation environment than Blender?

Do you really mean .01 scale, or the normal .1 scale?

I can put the old bone rotations back in, but there were actually two sets of transforms--what I had done myself, and then what I did to try to be conformant with niftools (which is the part I thought might not be working). Did you use the niftools flag? 

Anyway, I'm willing to have a go at this but I'm gonna need some handholding.

**Comment by BadDogSkyrim** [comment]
Something to try: Another guy is sucessfully using FBX by providing the following bone rotations:

            primary_bone_axis = 'Z',
            secondary_bone_axis = 'X',

Maybe those would allow your export to work?

**Comment by Akira13641** [comment]
I no longer think this is necessary TBH. I just re-imported my stuff with the stock Y forward, Z up, which works directly with the stock Y forward Z up in JGernandt's Blender HKX plugin. Basically the fact that PyNifly doesn't arbitrarily rename all the bones for no particular reason allowed me to use it in the process of making these, so far, so it's been very handy:
[Falmer rig](https://www.nexusmods.com/skyrimspecialedition/mods/102768)
[Werewolf rig](https://www.nexusmods.com/skyrimspecialedition/mods/102632)
