### ISSUE TITLE
NoneType object has no attribute 'name' error

### ISSUE THREAD

**Issue by TokyoSU** [BadDogSkyrim/PyNifly#173]
[SkyrimLE,Blender3.6]
Tried opening dockstepsdownend01.nif but it ended up as error:
![error_type](https://github.com/BadDogSkyrim/PyNifly/assets/77746747/4773c11d-5238-4cbf-ae9f-ea79ef967707)
EDIT: some files have this error, found 2 in the architecture folder but there is problably more.

**Comment by BadDogSkyrim** [comment]
Looks like maybe you tried to import a nif with something selected, and it wasn't an armature.

This should work, especially given that this isn't a skinned mesh. For now, just make sure you have nothing selected when you do the import.

**Comment by TokyoSU** [comment]
Nope tried without anything selected and it still throw an error, also it happen with many files:
```
farmhouse01walkway.nif
farmhouse02.nif
farmhouse02walkway.nif
farmhouse03.nif
farmhouse03walkway.nif
farmhouse04.nif
farmhouse04walkway.nif
farmhouse05.nif
farmhouse05destroyed01.nif
farmhouse05destroyed02.nif
fencewoven01.nif
fencewoven02.nif
lumbermill01.nif
lumbermill01waterwheel01.nif
lumbermill01waterwheel02.nif
smith01.nif
```

**Comment by BadDogSkyrim** [comment]
Yup. Damn.

**Comment by TokyoSU** [comment]
Checked the previous version (v12.0) and it happen on it too.

**Comment by BadDogSkyrim** [comment]
It's a block type that's not handled. I'll do better error checking and probly implement the block type.

**Comment by BadDogSkyrim** [comment]
Fixed in latest.
