### ISSUE TITLE
Empty weights after import-export on v9.0+

### ISSUE THREAD

**Issue by Craap** [BadDogSkyrim/PyNifly#175]
Might be a user error, but when I import and export SSE nifs on v9.0+, NiSkinData does not contain any vertex weights, so the verts go all over the place ingame.

Steps:
1. Import nif (default settings)
2. Don't edit anything
3. Select the mesh
4. Export nif (default settings, target game is skyrim SE)

Tested on v7.0, v.8.5, v9.0, v12.1, and blender 3.5.1.
Import and export are successful, console doesn't show any error.

When checking in nifskope, on v7.0 & v8.5 the vertex weights are there after exporting:
![8 5](https://github.com/BadDogSkyrim/PyNifly/assets/110075485/de627220-1f24-4b02-8f16-45c074a24343)

But on v9.0 & v12.1 they aren't:
![9 0](https://github.com/BadDogSkyrim/PyNifly/assets/110075485/bd40c1b0-7740-44e7-9bb1-29d3cb690986)

**Comment by BadDogSkyrim** [comment]
I see it. What the hell? I have tests for this.
