### ISSUE TITLE
Force childless node export option

### ISSUE THREAD

**Issue by AlecRFreeman** [BadDogSkyrim/PyNifly#176]
Previously I suggested allowing empty node tree export as they're often used to hold data for attachments #127, however it seems as of 12.1 and 12.0 this is no longer normal behaviour. I'm unaware of any custom properties for forcing export, but something similar is in the 3ds max workflow "sgoKeep" which forces a node to export for nodes like ProjectileNode or empty attach bones which need to be animated regardless of whether a mesh is attached.

Would it be possible to add a custom property tag which forces an empty to be exported regardless of lack of children? Either that or a checkmark on export to force all nodes to export would be a quick workaround.

**Comment by BadDogSkyrim** [comment]
Fixed in next release. If you select the empty, or select the root node and it's parent to an empty, the empty will be exported.
