### ISSUE TITLE
nif missing nodes / changed values

### ISSUE THREAD

**Issue by michaelsmolinski** [BadDogSkyrim/PyNifly#181]
First off, thank you for creating this blender addon!

Potential issues I am seeing is that round trip import/export results in a few nodes missing, a few values changed and a few nodes out of order.

The ones I am seeing on this particular Skyrim SSE mesh (farmhouse01.nif) are:

1. bhkRigidBody node (and child nodes) missing. Data appears to import into Blender - I see "bhkRigidBody in the scene collection; but doesn't export back out. I know mopp collisions are not supported, but I thought it would save the original blocks when exporting?
2. BSXFlags name value changed from 1 to 9
3. NiNode node missing
4. BSTriShape nodes - not in original order
5. BSTriShape nodes - flag changed from 524302 to 14 (missing Bit 19)
6. BSTriShape nodes - Bounding Sphere values changed

Some of these I'm not sure if it has an in-game impact, so some may be moot points.

I have attached the original nif and exported pynifly nif.

[farmhouse01nif.zip](https://github.com/BadDogSkyrim/PyNifly/files/13211744/farmhouse01nif.zip)

**Comment by BadDogSkyrim** [comment]
1. MOPP collisions aren't yet supported.
2. Bug
3. If loose nodes are selected on export they _should_ be exported, so maybe bug.
4. Order isn't guaranteed and never (almost never?) matters.
5. Bug.
6. I don't think it matters as along as the new bounding sphere is reasonable and isn't off by much.

**Comment by BadDogSkyrim** [comment]
Fixed in next release.
