### ISSUE TITLE
Mesh distortion in-game (Skyrim SE)

### ISSUE THREAD

**Issue by DamiLovesSunflowers** [BadDogSkyrim/PyNifly#186]
Before getting to the problem, your plugin truly makes the creation and edition of meshes way lot easier! Tysm for making it! :)

So, when making my own high poly meshes (and overwriting the original meshes) it looks perfectly fine when viewed through NifSkope or Blender, but gets horribly distorted in-game. I have covered every tri that was linked to its main nif but still get the same issue. Any advice? Also here's an example of a female head mesh.

<a href="https://imgur.com/oXwrH7L"><img src="https://i.imgur.com/oXwrH7L.png" title="source: imgur.com" /></a>

**Comment by podvornyakva** [comment]
It is probably wrong morf *.tri. Check in Blender.

**Comment by BadDogSkyrim** [comment]
Yes, looks like a mismatch between tri and your mesh. pyNifly exports tris with the head, so make sure they're all in the right place. If all else fails, remove all references to tris from the head record, verify that looks right, then add them back one at a time.

**Comment by DamiLovesSunflowers** [comment]
I'll see what I can do about it and try to report back. By the way I don't really feel like it might actually be COTR, for I tried to do the exact same thing using High Poly Head but the results still ended up the same as the image above, might be something I'm doing wrong idk.

**Comment by DamiLovesSunflowers** [comment]
OMG IT WORKED! Tysm!

For future people that may get the same problem, following PyNifly's wiki, to prevent that horrible mesh distortion from happening it is completely necessary to import the main nif and then a tri file that is connected to it (FemaleHead.nif and then BROW_FemaleHead.tri for example) and then exporting it as a tri file (file/export/Nif file with PyNifly) once finished. The main nif file and its main tri file (FemaleHead.nif and FemaleHead.tri for example again) shouled be exported at the end, those are the steps that worked for me at least.

Really, tysm for helping! :)
