### ISSUE TITLE
Exported dragon mesh exploding

### ISSUE THREAD

**Issue by andperks6** [BadDogSkyrim/PyNifly#194]
I'm trying to reduce the number of vertices on some obscenely high poly dragon meshes. The resulting mesh appears fine in nifSkope (need to enable Export Modifiers to save the modified vertices) but in game looks a lot like the '[exploding mesh](https://www.youtube.com/watch?v=pZWZFq-1B9s)' bug mentioned often with outfit meshes. I find it odd it happens here but assume some skinning data was lost/broken in the export.

I've tried a the suggestions I could find regarding 
- don't use the "Rename bones" and "Create bones" options, 
- import their skeletons first, or use the "Reference skeleton" 
-  import turn OFF "Create armature from pose position" and export set "Preserve bone hierarchy"

I don't see a new group called `"*UNWEIGHTED_VERTICES*"` which leads me to think vertices are weighted but the vertex weights all show as 0 in the NiSkinPartition Can you help troubleshoot this?
![image](https://github.com/BadDogSkyrim/PyNifly/assets/56888365/9185b07d-98a4-4d81-afe7-f95c1ef6ed4c)

[download assets here](https://app.box.com/s/qv9hov0qlm51vfu349et8h1nntfi04qr) the import and export nif, also included the attempted reference skeleton

**Comment by BadDogSkyrim** [comment]
Had a look but your original nif claims to be created with outfit studio and the other one was run through Nif Optimizer. Did you try with the export straight from Blender?

**Comment by andperks6** [comment]
apologies, I may have provided an export mesh I made further attempts to fix. I'll show the full workflow and give an export file straight from blender

first, importing without the 'create bones' and 'rename bones'
![image](https://github.com/BadDogSkyrim/PyNifly/assets/56888365/f1e9daf2-79b5-40a3-805a-36b65d8c460f)
results in a blender object that looks like this
![image](https://github.com/BadDogSkyrim/PyNifly/assets/56888365/2e3b4d86-cabd-47ab-bcf8-dcf9660243a5)

Which I then add a decimate modifier and copying to the selected items. Then after select hierarchy at the scene root, with only 'export modifiers' selected
![image](https://github.com/BadDogSkyrim/PyNifly/assets/56888365/0f33f5e1-f645-4e35-9d07-03c3bfbbc2da)

 [this](https://app.box.com/s/t1043omctbfqozs376mu92y7ec94g0va) is the resulting file
Let me know if there are any other steps you want me to take for troubleshooting

**Comment by BadDogSkyrim** [comment]
Import looks ok. The loose empties just mean that the nif includes bone nodes that aren't used.

Export makes me think you have an old pyNifly. that "Use Blender orientation" option should be a check box, and is in the latest version. Also you don't need "Export modifiers" tho I don't think it will break anything.

Check that you've got the latest version. I'll look into this more in the AM.

**Comment by andperks6** [comment]
That indeed was the issue. After using the latest release (and disabling rename bones) the mesh exported with no issues.

I had do hunt down where I downloaded an outdated version since this was an obvious mistake, turns out the download at [fallout 4 nexus](https://www.nexusmods.com/fallout4/mods/52319?tab=description) is for the 10.2 version, fyi.

Thanks for all the help!

**Comment by BadDogSkyrim** [comment]
K thx.
