### ISSUE TITLE
Exported NIF is invalid, causes CK to crash

### ISSUE THREAD

**Issue by praecipitator** [BadDogSkyrim/PyNifly#196]
I tried editing a nif in Blender, but the result turned out to be invalid: the Fallout 4 CreationKit crashes when I try to load the resulting nif in it. What I did to it was adding some more faces and editing UVs.

Blender Version: 4.0.2
V13.6

I uploaded both the .nif and the .blend here.

[WheelsTest.zip](https://github.com/BadDogSkyrim/PyNifly/files/13931702/WheelsTest.zip)

**Comment by BadDogSkyrim** [comment]
FO4 tends to be very whiney if you don't follow all its rules and I think that's what happened here.

First thing I did was paste a collision from another mesh (which had nothing to do with yours) and that loaded properly.

Then I took the collision back out and cleared the havoc flag from the BSX Flags node. That didn't work. But then I changed the flags on the root node to 14 and that did work.

So the game's expecting your mesh to have a collision. You can fiddle with the flags to convince it that it doesn't need a collision. Can't tell you more than that.

**Comment by praecipitator** [comment]
Interesting, I came to a different workaround yesterday: I erased the shader property of the post-blender nif, and replaced it with the one from the pre-shader nif.

**Comment by BadDogSkyrim** [comment]
Kinda sorta not surprising... some flags in the shader do have to be coordinated with other aspects of the nif. But I thought FO4 ignored the shader in the nif entirely, in favor of the materials file. (On the other hand, I have found FO4 nifs _without_ materials files, and they seem to work.)

**Comment by Aflaungos** [comment]
Try running the mesh in Elric
