### ISSUE TITLE
nifs exported causing CK to crash, but found a fix.

### ISSUE THREAD

**Issue by mrsandman89** [BadDogSkyrim/PyNifly#198]
i had fixed some bone weights in blender for a some outfit studio exported nifs and something breaks after blender export. selecting the nif to assign to a armor addon causes the CK to crash.

from testing and comparing other nifs exported with blender, what i have found is the addon breaks any material that has an attached environment map assigned in the bgsm.

to fix this.
1) export the nif - optionally remove all materials prior to export.
2) in nifskope remove all the BSLightingShaderProperty blocks and save 
3) either in nifskope or outfit studio reapply the shader and assign the bgsm, save(nifskope) or export to nif(outfit studio)
4) run the nif through Elric. no more crashing.

p.s. i really do love this addon for blender, makes weight painting and applying subsegment data a ton more enjoyable. thank you for this addon.

**Comment by BadDogSkyrim** [comment]
As always, if something doesn't work as you expect, import a similar nif and see what the importer did. That will work on export.

In this case, you probably have some flags that need to be set correctly for the environment map. FO4 is super-picky about those. Those flags are stored as custom properties on the material so you can set them as needed.
