### ISSUE TITLE
[Question] Supporting other games than bethesda one ?

### ISSUE THREAD

**Issue by TokyoSU** [BadDogSkyrim/PyNifly#204]
Hi,
1) I can open it using https://github.com/niftools/blender_niftools_addon but it's really not stable and not all the nif file is supported, would it be possible to support it later with pynifly ?
there a monster from the game, with kfm, nif, kf and the texture.
if you have time could you look at it ?
it came from the game "Grand Fantasia"
[M001.zip](https://github.com/BadDogSkyrim/PyNifly/files/14521687/M001.zip)
KFM version: 2.2.0.0b
NIF version: 20.2.0.8
KF version: 20.3.0.9

2) Don't know if blender can support NiParticleSystem node or NiBillboardNode (it's not related to the question above)
but i would like it if it can be supported :)

EDIT: i've seen the `My interest is primarily Skyrim, Skyrim SE, and Fallout 4 so I'll be focusing on supporting those games.` in the readme :x sorry to have asked.

**Comment by BadDogSkyrim** [comment]
I'm always happy to hear suggestions. Grand Fantasia doesn't look like my cup of tea--I prefer better graphics. That's a real low-poly mesh right there, and I don't love the in-game graphics. Right now I've been playing Cyberpunk 2077 and wondering what it would take to support that game. 

I'd like to support more node types. Next up most likely is constraints, I'll have a look at particleSystem and Billboards.

**Comment by TokyoSU** [comment]
No problem, everyone have different opinion about games :)
Hope to see Grand fantasia supported someday :D
