### ISSUE TITLE
4.1 changes to the python API remove some properties used by the add-on

### ISSUE THREAD

**Issue by Novelyst** [BadDogSkyrim/PyNifly#206]
Because of the changes found [here](https://developer.blender.org/docs/release_notes/4.1/python_api/#mesh), mesh import and export do not work in 4.1. Specifically, Mesh.use_auto_smooth has been removed and this affects the import process. I think line 313 in \_\_init\_\_, `the_mesh.use_auto_smooth = True` can just be removed/put into a try/except. The other removed feature, Mesh.calc_normals_split(), is used three times, once in \_\_init\_\_ and twice in tests. I think the one in init can be moved the the `try:` above it. For the tests, I'm not familiar with their purposes so I've set them to FALSE for now for myself. Import and Export seem to work.

**Comment by BadDogSkyrim** [comment]
I'll check it out. Freakin' A, I wish Blender would at least preserve backwards compatibility in minor version updates.
