### ISSUE TITLE
Blue Channel of Normal Map Inverted in Shader Instead of Green

### ISSUE THREAD

**Issue by Sync-67** [BadDogSkyrim/PyNifly#207]
I noticed a shading issue on imported NIFs being caused by the conversion of the normal map from DirectX to the OpenGL format. The shader set up has the blue channel of the normal map being inverted and used as the green channel when recombining. I think the nodes just got mislinked when it was intended for the green channel to be inverted.

![Nodes](https://github.com/BadDogSkyrim/PyNifly/assets/92419418/c9b0ce49-2578-4872-bf97-6a364f8aba51)

**Comment by BadDogSkyrim** [comment]
Fixed in latest.

**Comment by Sync-67** [comment]
Model space normals for character meshes import correctly, but this is an issue on standard normal maps, like the ones used for architecture meshes. The nodes are still being generated incorrectly with PyNifly V14.5.2 and Blender 4.1.

https://github.com/BadDogSkyrim/PyNifly/blob/c181744691103754d9e03a1d1924a2a9ae6cc1bb/PyNifly/shader_io.py#L359

The index number of the output being inverted still points to the blue channel. Changing the index to 1, so it points to the green channel fixes the issue for me.

**Comment by BadDogSkyrim** [comment]
Crud, ok I'll check.

**Comment by BadDogSkyrim** [comment]
Fixed.
