### ISSUE TITLE
HKX animation import error

### ISSUE THREAD

**Issue by Kayhotic** [BadDogSkyrim/PyNifly#210]
![image](https://github.com/BadDogSkyrim/PyNifly/assets/36052934/666e463e-c097-4771-9a9d-2869423464f4)
![image](https://github.com/BadDogSkyrim/PyNifly/assets/36052934/44829ab7-fde6-4f6f-a1fa-5aa1bd046380)

not sure what i could be doing wrong. but it seems HKX animations are not importing

**Comment by BadDogSkyrim** [comment]
Is that HKX file a standard game idle? I think I'm going to have to give it a try on this end.

**Comment by Kayhotic** [comment]
as far as im aware it is. ive tried numerous HKX animations from FO4 with the same result

**Comment by TokyoSU** [comment]
Having that error with any animation from FO4 too, it didn't say any specific error, only xml creation error :'(

**Comment by beefclot** [comment]
This error is happening because importing is calling "HKXCMD CONVERT -V:XML {tmp_filepath} {xml_filepath}" on the file being copied. This is annoying, because nowhere does PyNifly specify that we need to have HKXCMD at x location, or at least in the PATH env var.

**Comment by BadDogSkyrim** [comment]
Guys. The page on animations does say "for Skyrim LE only".
