### ISSUE TITLE
"rotated nodes?" scrambling mesh

### ISSUE THREAD

**Issue by MattCowdery** [BadDogSkyrim/PyNifly#211]
Exporting a body mesh with PyNifly that I made and weighted in blender (with an imported skeleton) results in a scrambled mesh in game. Trying to trouble shoot this myself, I found that toggling "node visibility" in outfit studio showed a rig-adjacent-shape on the ground (which does match up to some of the animation scrambling I'd been having) The problem is, I dont *really* know what these "nodes" are here, or how I can stop this from happening. 
![image](https://github.com/BadDogSkyrim/PyNifly/assets/13543088/622e9901-960d-41b8-8e8c-dfaa0f52dcfd)
![correct mesh](https://github.com/BadDogSkyrim/PyNifly/assets/13543088/6b60678d-6c61-4b0d-b3a6-a33b691f57bd)

(The result of this is a mesh that looks like this in game )
![problem 1](https://github.com/BadDogSkyrim/PyNifly/assets/13543088/b18d2752-4c31-4037-82b3-fd3dd64d66d4)
here is the nif itself, in case that helps
[problem mesh.zip](https://github.com/BadDogSkyrim/PyNifly/files/15137031/problem.mesh.zip)

Any help is appreciated, thanks

EDIT: appears solved by deselecting "preserve bone heirarchy" on export, and then selecting "fix bad bones" in Outfit Studio. Leaving post up in case it helps another confused modder. 
(Thanks for all you do for the modding community)

**Comment by BadDogSkyrim** [comment]
I'll have a look. It should work out of the box. Not sure why you would want to preserve bone hierarchy for a bodypart?

It's possible that you have, like, the ZeX skeleton and then it's trying to export using the vanilla skeleton. But you'd have to be doing extra work to make that break. It will take me a few days, but I'll look.

**Comment by BadDogSkyrim** [comment]
I had a look. The only thing I can guess is that your skeleton is hinky--maybe you loaded it using the niftools importer, or with an older version of pynifly.

Best thing to do if you're continuing to work on the mesh is to disconnect the mesh from the armature, delete the armature, import the skeleton with the latest pynifly, either by importing a body mesh or the whole skeleton nif, and reconnecting the body to the new armature.
