### ISSUE TITLE
Discrepency with importing NIFs between version 14.6.2 and 10.5.0

### ISSUE THREAD

**Issue by savagegunderson** [BadDogSkyrim/PyNifly#219]
Preface: I have been using version 10.5.0 for years and only opted to upgrade to 14.6.2 seeing as it is meant to be compatible with Blender 3.x (I am primarily using Blender 3.6.10)

When importing a Fallout 4 head nif (in this case a headgen file that contains all of the parts) on version 10.5.0 with the default settings toggled, the mesh imports correctly with all of the respected face parts in the correct location in respect to the location of the generated armature.

When doing the same with version 14.6.2, regardless of options selected, importing the same mesh causes the face parts to be disjointed and in a different location.

Import process and results in version 10.5.0
https://github.com/BadDogSkyrim/PyNifly/assets/103076427/ce96c862-d5f5-4c8d-adb2-a9097422ebb3

Import process (with default settings) and results in version 14.6.2
https://github.com/BadDogSkyrim/PyNifly/assets/103076427/7b1e2dcf-3267-46f5-a6c6-dbc3827c7751

Note: I do not mind having to reparent the objects from 10.5.0 to the armature seeing as they are in the correct location on import, the only other change I ever had to make with this version was resetting the bone scale, rotation, and location in pose mode.

ADDED INFORMATION IN POST.
When using version 14.5.2 on Blender 4.1.1 the location issue does NOT exist.

When using version 14.6.2 on Blender 4.1.1 the same location issue DOES exist.

**Comment by BadDogSkyrim** [comment]
Should be fixed in 14.7.

**Comment by savagegunderson** [comment]
confirming version 15.0 fixes this issue.
