### ISSUE TITLE
Shader Issue between versions 10.5.0 and 14.5.2 and 14.6.2

### ISSUE THREAD

**Issue by savagegunderson** [BadDogSkyrim/PyNifly#220]
Small thing I noticed, but when importing a head mesh with geometry based alpha properties in Blender 3.6.10 with PyNifly version 10.5.0, it would attempt to create a shader that replicated the geometry based alpha property as seen on the model in NifSkope where as there is no attempt of this in PyNifly versions 14.5.2 or 14.6.2

in NifSkope
![image](https://github.com/BadDogSkyrim/PyNifly/assets/103076427/483f321f-fc44-4773-9744-8f90a4db655f)

In Blender 3.6.10 with PyNifly version 10.5.0
![image](https://github.com/BadDogSkyrim/PyNifly/assets/103076427/4a7d322c-e8a0-4d2f-a9c3-36aa6adeb2f3)

In Blender 4.1.1 with PyNifly version 14.5.2 (14.6.2 is set up the same way shader wise.)
![image](https://github.com/BadDogSkyrim/PyNifly/assets/103076427/95cf291e-fd9b-4be8-924e-5d18ff6ab71b)

**Comment by BadDogSkyrim** [comment]
Thanks for the report. I'll update the shader.

**Comment by BadDogSkyrim** [comment]
Fixed in next.
