### ISSUE TITLE
[Import] skeleton.hkx failed. v17.0 Blender 4.2.1

### ISSUE THREAD

**Issue by TokyoSU** [BadDogSkyrim/PyNifly#238]
After trying the last update, i get this error:
![Capture](https://github.com/user-attachments/assets/4d4c3480-b633-49c3-b2e5-a30da3b4b190)
Possibly the import is missing.
Using Steam Skyrim LE

**Comment by BadDogSkyrim** [comment]
That's bizzarro. Try reinstalling pynifly.

link_to_collection is a new routine in 17.0, but it's definitely there in the code. I can only guess you've got some old files there.

**Comment by TokyoSU** [comment]
That's right, weird, i did remove it from the addons, it seem i need to remove the plugin folder too :x thanks :)
