### ISSUE TITLE
eyeschild.tri Skyrim

### ISSUE THREAD

**Issue by LittleMissF** [BadDogSkyrim/PyNifly#254]
eyeschild.tri Skyrim LE/SE can't be imported, makes it impossible to edit children eyes.

**Comment by BadDogSkyrim** [comment]
Looks like a weird tri file. There are some ways tri files can be "wrong" yet work in game. There's also two variants, one of which is almost never used. This might be that variant.

**Comment by LittleMissF** [comment]
My problem is, when I make a new one, it happens again. Any insight what I need to fix on the mesh, so it doesn’t happen again. I wondered if it’s maybe because the kids have no chargen.

**Comment by BadDogSkyrim** [comment]
You mean, you create a new set of tris for the eyes in Blender, export, and the exported tri can't be read? Cuz that shouldn't happen.

**Comment by LittleMissF** [comment]
Exactly that. That’s why I opened up an issue here. I was really surprised as that happened, because it shouldn’t. I made new tris, as I wanted to import those, I had the same issue happening.

**Comment by BadDogSkyrim** [comment]
Huh. If you send me the .blend file I can have a look.

**Comment by LittleMissF** [comment]
Can‘t you replicate the issue? Load in the eyes, create a shape key, call it test, export it all. Then open a new blend file import those eyes and try to import the new TRI file you just made. I literally have no blend file to give you. Because that’s all I did, then I started to change the UV on the mesh, wanted to import the new Tri again, had the same issue, came here. I didn’t even bother to keep the blend file. Because I don’t make myself work on eyes I can’t export. I can create one and send it to you, with the new Tri.

**Comment by LittleMissF** [comment]
So I tested it again, and it’s after morphing the eye shapes from one TRI to the other, that breaks it for the eyechild. That doesn’t normally happen. I had to go through the process what I did to find the moment they break. So the child eyes are truly impossible to edit in blender then, without fully redoing the expressions tris by hand? Nor can it be fixed to use the original assets? Like beast eyes, they have the same issue.

**Comment by BadDogSkyrim** [comment]
I have a fix just about ready to go. I'll run full tests in the morning and post a kit. 

Problem is that there's a style of morph that wasn't being handled correctly. It's hardly ever used, so I haven't seen the issue before.

**Comment by LittleMissF** [comment]
Oh gosh, if you have a fix, that would be awesome. I always thought it’s known. As well the same issues with beast eyes. I am probably one of the rare people editing eyes in blender and making TRI files. Be it morphed or from scratch. This would mean I could finally edit all eyes. Thank you so much for looking into it, so very appreciated.

**Comment by BadDogSkyrim** [comment]
I posted a fix in the latest rev. Give it a try.

**Comment by LittleMissF** [comment]
This is so AMAZING! I am able to export finally childhead, argonian eye, both khajiit eyes without warning. 
I can export the childeye, it throws me a "exported with warnings" thou:

"Python: Traceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_export_tri.py", line 167, in poll
    return (context.active_object != None) and ((context.active_object.type == 'MESH') or (context.edit_object.type == 'MESH'))
AttributeError: 'NoneType' object has no attribute 'type'

**Comment by LittleMissF** [comment]
Are you able to import TRIs exported over  jg1 Tri Morph Plugin into the eyes?

**Comment by BadDogSkyrim** [comment]
Glad it's working.

That error generally means you don't have anything useful to export. In this case it looks like a minor bug, checking for an "edit object" when there isn't one. You can ignore it.
