### ISSUE TITLE
Handle imported shapes with transform/rotate overrides

### ISSUE THREAD

**Issue by thomasandersen** [BadDogSkyrim/PyNifly#39]
I guess it is a bad practice, but some nifs including BGS's nifs have the transform/rotation values overridden in the shape node.

Example nif: Fallout 4 - SetDressing/Vehicles/Crane03.nif

1. Open the nif in NifScope and find the BSTriShape named 'Glass:0'
2. Right click on the BSTriShape node and select Transform/Edit

See the shape's translation and rotation is not reset / applied (or what it is called)

PyNifly seems to ignore the shape node transform/rotations. 

I guess this is not a high priority issue, but nice to know as it seems like many users does transform edits in e.g. NifScope etc.

**Comment by BadDogSkyrim** [comment]
I have a few meshes that aren't importing properly and I think this is at least one of the reasons. Transforms are the bane of my existence. I think the right thing to do is ignore the transform if the shape is skinned, but apply it if it's not.

**Comment by BadDogSkyrim** [comment]
Problem found and fixed. Will be included in V1.1.
