### ISSUE TITLE
Quality of life : Apply modifiers on export

### ISSUE THREAD

**Issue by thomasandersen** [BadDogSkyrim/PyNifly#40]
It would be nice to have an option to 'auto apply' all modifiers in the export dialog.

1. Create a standard cube
2. Add a bevel modifier
3. Export with nifly

Actual result: The bevel modifier is not applied on the result nif
Expected: Have an option in the export dialog to apply all modifiers. See the built-in obj exporter.

I guess the vanilla obj exporter just applies modifiers in the order as seen in the UI/modifier stack (e.g. from top to bottom)
Probably not ideal in some cases, but better than nothing.

**Comment by BadDogSkyrim** [comment]
Yeah, good idea. I don't know how the obj exporter is doing it but sure, it's a pain to have to apply them to export.

**Comment by BadDogSkyrim** [comment]
Done.

**Comment by dev-nll** [comment]
> Done.

It's not working for me with the latest version of PyNifly. I applied a decimate modifier to reduce poly count.

![image](https://github.com/BadDogSkyrim/PyNifly/assets/1366642/161693bc-98db-43b1-8c36-1bcd33c10075)

But when I export the NIF, the number of polys is unchanged. So the modifier is not exporting.
