### ISSUE TITLE
Wrong weights when skeleton is not renamed

### ISSUE THREAD

**Issue by kamicane** [BadDogSkyrim/PyNifly#54]
When the skeleton is not renamed upon importing (unticking the rename option), weights are still assigned to the `.L` / `.R` bones. The weights with the original bone names are empty.

![bonz](https://user-images.githubusercontent.com/7131/131367538-56c72692-428f-40b6-9a2b-68a8d8e0f2d3.png)

**Comment by BadDogSkyrim** [comment]
Ugh. Thx, looking at it now.

**Comment by kamicane** [comment]
Works perfectly in 1.2, thank you!

![run](https://user-images.githubusercontent.com/7131/131891896-adbf29fe-d4a8-42f2-ad52-26dff28ec459.png)
