### ISSUE TITLE
Feature request: Import normals

### ISSUE THREAD

**Issue by kamicane** [BadDogSkyrim/PyNifly#57]
Right now normals seem to be ignored during import. This is mostly visible on uv seams, but any custom normal is lost.

**Comment by BadDogSkyrim** [comment]
Yup, you're right. It's the kind of thing that could be an option on import, or could just have the user delete custom normals if they don't want them. The seam thing is a big deal--I have to merge the seams in Blender to fix that.

**Comment by BadDogSkyrim** [comment]
Implemented in 1.6
