### ISSUE TITLE
Handle directx normal maps on import

### ISSUE THREAD

**Issue by kamicane** [BadDogSkyrim/PyNifly#61]
Directx tangent space normal maps have an inverted green channel compared to opengl normal maps (the format blender uses).

I have been fixing it by inverting the green channel in the shader like so:

![InvertGreen](https://user-images.githubusercontent.com/7131/132395833-6c9bdd82-cf8c-4eb5-a5bb-d13a5bb50c71.png)

Would be cool if pynifly could do this automatically on import, like it separates red and on the specular maps.

Results:

Directx (inverted green)

![directx-normals](https://user-images.githubusercontent.com/7131/132396117-37284dcd-2fb8-42f0-b756-e4ace66ef0ea.png)

OpenGL (non-inverted green)

![opengl-normals](https://user-images.githubusercontent.com/7131/132396137-ef4651ec-d705-4069-a409-874ee7b1bae5.png)

**Comment by BadDogSkyrim** [comment]
Is there any way to recognize a directx normal when you see it? Is there a particular nif version or game?

**Comment by kamicane** [comment]
Every fallout 4 normal map is in directx format. Never really did any Skyrim modding so not sure what format it uses, or if it even uses tangent space normals?

**Comment by BadDogSkyrim** [comment]
F*ck, srsly? Like probably all of mine. Likely that explains some of the weird behavior I've seen. Plus calls into question every tool I use to handle normals. My whole life is a lie.

**Comment by BadDogSkyrim** [comment]
Fixed in latest rev.
