### ISSUE TITLE
Export BSFadeNode on demand

### ISSUE THREAD

**Issue by BadDogSkyrim** [BadDogSkyrim/PyNifly#65]

**Comment by tokitoki22** [comment]
Thanks you confirm.  I actually convert to NiSkininstance in nif scope  and add  FadeNode, then change link again t,and set partion correclty.  to edit nif work in game.  My current edit facegen.nif are mostly made by LE then convert to SE long time ago., so I do not know if  there will be some difference about node.  (may test again with SE original facegen.nif too)

And no need to rush  about this issue.  As future I may hope this add on more easy  import >> edit >>  export these NPC facegen.nif, without many nif-scope work.. (I actually still not understand clear how each node means, and manage in nif-scope as I need..)

**Comment by BadDogSkyrim** [comment]
This is implemented.
