### ISSUE TITLE
Pretty sure that the issue with texture files wasn't fixed

### ISSUE THREAD

**Issue by johnsone006** [BadDogSkyrim/PyNifly#68]
So today, I tried to import .nif file into blender, but it said that some texture files weren't found. But of course they weren't-first off, the file paths of the supposedly missing files skipped one of the folders, and the console window had two backslashes in between each folder of the file path to the files that were supposedly missing. None of the folders or file names have backslashes in them. I have confirmed that all three texture files are, in fact, on my computer, they just aren't in the exact same folder. Like for example-this isn't the real file path, but just to give an idea-two of the textures may be located in C:\Users\MyUserName\Desktop\SEObjects\Objects Vanilla\Textures\textures\stuff\sovngarde (the third one has the same file path up until the folder named textures) whereas the mesh might be located in C:\Users\MyUserName\Desktop\SEObjects\Objects Vanilla\Meshes\meshes\stuff\sovngarde
I'm using blender version 2.90. 
I'll copy and paste what the console window said below, and then edit my username out of all the file paths (so the text doesn't seem to want to paste properly, so I'll bold the file paths that have two backspaces between each folder):
Read prefs: C:\Users\MyUserName\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend
found bundled python: C:\Users\MyUserName\Downloads\blender-2.90.0-windows64\blender-2.90.0-windows64\2.90\python
Info: Deleted 1 object(s)

Warning: This script was written Blender version 2.92.0 and might not function (correctly), though it is enabled

Must select an object to export
Must select an object to export
. . Some texture files not found: **['C:\\Users\\MyUserName\\Desktop\\Skyrim Creation Kit Objects\\Objects Vanilla\\textures\\architecture\\sovngarde\\SOVFloor02.dds', 'C:\\Users\\MyUserName\\Desktop\\Skyrim Creation Kit Objects\\Objects Vanilla\\textures\\architecture\\sovngarde\\SOVFloor02_n.dds', '', '', 'C:\\Users\\MyUserName\\Desktop\\Skyrim Creation Kit Objects\\Objects Vanilla\\textures\\cubemaps\\ShinyBright_e.dds', '', '', '', '']**
Import of nif failed
Traceback (most recent call last):
  File "C:\Users\MyUserName\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nifly\__init__.py", line 895, in execute
    NifImporter.do_import(self.filepath, flags)
  File "C:\Users\MyUserName\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nifly\__init__.py", line 853, in do_import
    imp.execute()
  File "C:\Users\MyUserName\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nifly\__init__.py", line 814, in execute
    self.import_shape(s)
  File "C:\Users\MyUserName\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nifly\__init__.py", line 668, in import_shape
    obj_create_material(new_object, the_shape)
  File "C:\Users\MyUserName\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nifly\__init__.py", line 242, in obj_create_material
    import_shader_attrs(mat, bdsf, shape)
  File "C:\Users\MyUserName\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nifly\__init__.py", line 184, in import_shader_attrs
    shader.inputs['Emission Strength'].default_value = attrs.Emissive_Mult
KeyError: 'bpy_prop_collection[key]: key "Emission Strength" not found'
Must select an object to export
Button '' in menu 'TIME_MT_editor_menus' is a menu item with unsupported RNA type 5

**Comment by BadDogSkyrim** [comment]
Ignore the double backslashes. Python does that when it's printing strings so you can paste them back in.

The importer hopes your textures are in the same file tree as your nif. If they aren't, nothing should break tho.

It looks like the problem is the shader doesn't have an "Emission Strength" input, which is likely a typo on my end. Will look.

**Comment by BadDogSkyrim** [comment]
Fixed.
