### ISSUE TITLE
Skyrim SE femalehead.tri can not import for facegen head.nif

### ISSUE THREAD

**Issue by tokitoki22** [BadDogSkyrim/PyNifly#72]
I hope to edit old cusotm follower facegen in blender. then follow wiki. Import facegen.nif have no problem. but without import tri files.  exported (from blender) nif not generate BSDynamicTriShape node. then I get the BSTriShape nodes for the facegen nif. 

So I try to import femalehead.tri (it should be much as current face part mesh = FemaleHeadNord object.) with select the head part. as object mode.    Then I only get these error log .

`Traceback (most recent call last):
  File "C:\Users\TAKE\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\trihandler.py", line 391, in from_file
    tri.read(file)
  File "C:\Users\TAKE\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\trihandler.py", line 313, in read
    raise ValueError("Error reading TRI file")
ValueError: Error reading TRI file
Import of tri failed
Traceback (most recent call last):
  File "C:\Users\TAKE\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\__init__.py", line 1125, in execute
    import_tri(self.filepath, bpy.context.object)
  File "C:\Users\TAKE\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\__init__.py", line 1006, in import_tri
    log.debug(f"Selected mesh vertex match: {len(cobj.data.vertices)}/{len(tri.vertices)}")
AttributeError: 'set' object has no attribute 'vertices'`

My blender version is 2.93 LTS 

I use MO2 as mod manager, then test both case (running blender from MO2 then load from virtual data directory /  directly load  file without use MO2.  it show same error. and not generate shape keys.   so it seems not matter.

At same time, Is there way without import tri, but just edit and export se face gen nif  but  generate as BSDynamicTriShape?  I do not plan to edit face tri morphs. but just need detail adjust for face gen meshes.  About LE version mesh,  I have way to copy and paste vertex position only with nif scope. or nif tools..  but about SE, we do not have the way I think.. (it corrupt nif)

**Comment by BadDogSkyrim** [comment]
The core problem here is that your tri file is corrupt, or at least malformed. The UV in the tri file should match the verts in the tri file, but your tri has 996 verts but only 918 UV verts. 

I don't know how this tri is even working. I guess that since the UV isn't actually used in game it doesn't matter that it's wrong. I can make the import more robust, so it ignores the UV if it doesn't match the verts, but right now that's your issue.

Since you want a BSDynamicTriShape and I haven't yet given you a way to do that directly, just add a chargen or expression morph using the shape keys. Then when you export you'll get the BSDynamicTriShape and just throw away the tri file that gets generated. I'll add a more direct way to specify what you want on export in the future.

**Comment by tokitoki22** [comment]
I see.  thank you clear inform those detail.  yes I suppose these mods tri may not keep UV correctly, but just generate vertex data (position)   then about UV, skyrim se  only use the  nif UV , I suppose..  (when generate shape key we do not need to import obj/FBX  with UV in blender, maybe it seems same logic..)

Maybe even though  tri file is not correct about UV and corrupted,  those mod offer tri just over-write, default skyrim SE head parts  tri files.  then when vertex order, and count is much with nif, it may work in game. as morph.  After reprot this,  I try to import Race menu offer tri files for NPC face parts.  those tri seems well made, then  PyNifly correctly generate shape keys. thanks.  

I suppose,  I can export nif as BSDynamicTriShape,. at least for head , mouth, eye part.. then I may copy paste node to original. with nif scope. may work?    or I may  import hair tri too.  anyway I will  try lager. And I really thanks your all effort and this great add on.   I dream long time,, if I will easy import and export SE nif and tri for blender  2.8. without tweak around, or convert nif etc, with change  many setting..  This add on already offer way (Today I try to make collision with this add on, then could  exchange bed collision without problem for SE (with chunk merge) really thanks.
I keep to use this add on often. and may report if I could find some issue...

**Comment by BadDogSkyrim** [comment]
Yeah, maybe I'll do collisions one day, but they're hard.

Pynifly will preserve vert order, so you can export and use the old tri and it should work.
