### ISSUE TITLE
Corrupt Tri error due to UV coordinates not equal to vertices

### ISSUE THREAD

**Issue by poisenbery** [BadDogSkyrim/PyNifly#77]
"Number of verticies differs from number of UV coordinates: 918 != 996
TRI file has valid header, but file appears to be corrupt
   !! Since 'Base Verticies' != 'UV Coordinates', file is probably corrupt.
However, if TRI file is *not* corrupted, then it is possible that Author's
assertion regarding TRI files always correlating V and UV array indices
might be wrong.
   Probably should post if you see this error and are sure file is not corrupt"
   
   
   I was trying to import the tri files from the expressive facial expressions mod for Skyrim SE. The tri imports with a different tool and works in game. I assume this means it's not corrupt.

**Comment by BadDogSkyrim** [comment]
Yeah I think what's up is that tris have a little more flexibility than the tool calls for. In this case, no one cares about the UV for facial expressions but the importer chokes on it. I have it on my list to fix.

**Comment by BadDogSkyrim** [comment]
Done in 1.6
