### ISSUE TITLE
Unnecessary multiple-partitions warning reported

### ISSUE THREAD

**Issue by BadDogSkyrim** [BadDogSkyrim/PyNifly#79]
If the boundary between partitions coincides with the boundary between UVs, when the system splits the verts along the boundary, some faces may end up in both partitions. The system will only consider a face in a partition if ALL its verts are in the partition, so after the splitting happens all the other verts that make up the face have to be in the partition. BUT since the verts are split they aren't in the initial mesh so the verts can't be added to the MULTIPLE_PARTITIONS error partition. See the panther male head.

**Comment by BadDogSkyrim** [comment]
...so the thing to do is tie the split vertex back to the original and put the original in MULTIPLE_PARTITIONS

**Comment by abaczkowski** [comment]
Is this issue the source of the 'Some faces have been assigned to more than one partition, which should never happen' caution traceback that happens with exporting?

**Comment by BadDogSkyrim** [comment]
Yes. It actually should be fixed now. Any such messages you get should reflect real errors.

I report it because I have had meshes cause a CTD because their partitions were messed up. But it doesn't always happen.
