### ISSUE TITLE
Exporting grass nifs ruins nif structure

### ISSUE THREAD

**Issue by JonnyWang33** [BadDogSkyrim/PyNifly#84]
[Image After/Before](https://cdn.discordapp.com/attachments/472571934463229953/938305135862505482/unknown.png)

**Comment by BadDogSkyrim** [comment]
1) You're exporting in Skyrim LE format but your input was SE. Was that intentional?

2) I haven't implemented other types of top-level nodes. You can easily convert to a FadeNode in nifskope.

**Comment by BadDogSkyrim** [comment]
Full support now implemented.
