### ISSUE TITLE
Non-Character Armatures

### ISSUE THREAD

**Issue by macronomicus** [BadDogSkyrim/PyNifly#86]
Seems like I ran into an edge case.  You can test yourself using a bow weapon from SSE.  Imports fine but the armature is blown apart on export.  It does not do this for character related nifs, so my guess was that you didnt add the needed bits to handle that particular armature case?

I found a workaround for now, using the olde blender 2.83 and niftools addon, convert nif to LE then import to blender, tinker, then export and bones etc are all in place.  So no rush or demands or anything, you may not even want this feature, since mostly nifly is for character stuff anyhow, still I thought I'd let ya know just in case its useful.

**Comment by BadDogSkyrim** [comment]
I'll check it out. Generally speaking, you should import but use the flag so that it doesn't add extra bones. On export, the bones should be flat (not in a hierarchy) but all the nifs I've worked with, that doesn't matter--the nif works anyway.

**Comment by macronomicus** [comment]
> 

Thanks man, I will keep that in mind, I guess I assumed that since they were flattened when viewing in nifskope, that it was borked, it could have been something else I did that broke the mesh from working in game that round. 

I will try more tests and keep in mind what you've said.  I appreciate the remarks, and the great addon too, its a lot faster than the niftools one, and works great in blender 3.

**Comment by BadDogSkyrim** [comment]
Fixed.
