### ISSUE TITLE
Can't enable plugin

### ISSUE THREAD

**Issue by DaXmAn** [BadDogSkyrim/PyNifly#89]
Traceback (most recent call last):
  File "...\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "...\Blender\3.0\scripts\addons\io_scene_nifly\__init__.py", line 91, in <module>
    def transform_to_matrix(xf: TransformBuf) -> Matrix:
NameError: name 'TransformBuf' is not defined

**Comment by BadDogSkyrim** [comment]
Not sure how that could be undefined. Maybe there was some issue building the kit, but I'm running with that kit. I'll look. You're installing from the zip, ya?

**Comment by DaXmAn** [comment]
Yes, from the zip.

**Comment by JustinGlen75** [comment]
Hello! First off, @BadDogSkyrim I love this plugin -- I was able to import a custom-made sword mesh into SSE VERY easily with this. Thank you! I have Blender 3.1 and I had a similar experience when trying to enable the latest plugin version (v4). I had v1.2 (I think) installed so I decided to remove it (within Blender > Add Ons) and then installed the new one. Like @DaXmAn, it installed fine but I too was getting some errors once I was trying to enable it. After just closing out Blender completely and restarting the application, I was then able to enable the plugin -- and verified that is was the newer version. I don't know if that will work for everyone but that is what seemed to work for me :)

**Comment by DaXmAn** [comment]
Well... that did the trick... previously I was not re-starting Blender... Thanks for sharing the info!

**Comment by JustinGlen75** [comment]
Absolutely! Glad it worked for you!

**Comment by BadDogSkyrim** [comment]
Glad you got it working. The wiki section on installing does actually mention that you might have to do this. Just sayin.

**Comment by DaXmAn** [comment]
True! Sorry I didn't read that. Sometimes I am too eager to work on stuff I assume I know everything ;) and I don't read all instructions.
