### ISSUE TITLE
AttributeError: type object 'Matrix' has no attribute 'LocRotScale' (Blender 2.93)

### ISSUE THREAD

**Issue by AshbeeGaming** [BadDogSkyrim/PyNifly#90]
Blender v2.93 throws up this error "AttributeError: type object 'Matrix' has no attribute 'LocRotScale'" whenever I try to import a NIF file, tried a variety of both LE and SE models. Only having this issue with V3 and V4. However, Blender v3.0 imports everything correctly. Is only Blender v3.0 supported from V3 up? Apologies if you've already clarified this somewhere.

Thanks,
Really love this plugin btw, it's immensely helpful!

**Comment by BadDogSkyrim** [comment]
Yeah, turns out LocRotScale was introduced in V3. In general I plan to focus on the latest version of Blender but I think I can do without this function. I'll see if I can back it out in the next version.

**Comment by BadDogSkyrim** [comment]
Fixed in latest release
