### ISSUE TITLE
Version 4.0.0 Exports Meshes to BSDynamicTriShapes when no Shape Keys Exist

### ISSUE THREAD

**Issue by Sync-67** [BadDogSkyrim/PyNifly#91]
Hello,

I've run into an issue with the most recent release (v 4.0.0) where exporting meshes to Skyrim SE will result in a Nif file with a BSDynamicTriShape even when no shape keys are present in the object data.

Importing a vanilla Skyrim SE mesh and exporting it to Skyrim SE without any changes still results in a BSDynamicTriShape being created for me, so unless I've completely missed something, I think there's a bug related to detecting shape keys. 

I'm using Blender version 3.1.0 to export the meshes.

Please let me know if there's more information I can provide that'll help. And thanks for creating this awesome tool!

**Comment by BadDogSkyrim** [comment]
Can't reproduce. What nif are you using to test?

**Comment by Sync-67** [comment]
I tested out a few clutter and static items but got BSDynamicTriShapes each time:
- meshes\clutter\common\archerytarget01.nif
- meshes\clutter\barset\barstraight01.nif
- meshes\dungeons\dwemer\walls\dwewallhalf01.nif
- meshes\armor\amuletsandrings\goldringgo.nif

I've uploaded a zip file with the vanilla meshes I imported, the Blend files, and the Nif files that I exported here: (https://drive.google.com/drive/folders/1VtXai1G1ApaGq7MgIgipqAAikdhxCX-l?usp=sharing)

I was thinking Blender 3.1 is fairly recent (March 9th, I think?) so I'm going to try on version 3.0.0 here after it downloads.

**Comment by Sync-67** [comment]
Okay, so I found out that Blender version 3.0.0 combined with PyNifly 4.0 has the same issue where it only exports BSDynamicTriShapes.

However, PyNifly version 3.0 will export BSTriShapes correctly with Blender 3.0.0 and 3.1

**Comment by BadDogSkyrim** [comment]
Dunno, still can't reproduce it. I can export those meshes properly whether I use your files or import the nifs and export them.

I just put 4.1 up--try with that and see if anything changes.

**Comment by Sync-67** [comment]
Good news! Version 4.1 fixed the issue and correctly exports BSTriShapes. So whatever was happening seems to be fixed now.

Thanks for your help!
