### ISSUE TITLE
Fallout 76 Nifs Not Loading

### ISSUE THREAD

**Issue by K3NNY4STRO** [BadDogSkyrim/PyNifly#98]
Title. When trying to import nifs ripped from fallout 76 with BAE, this error message appears and the model does not appear.
![image](https://user-images.githubusercontent.com/103604576/163259339-80336768-751a-42b2-b6d7-fd6817094a1a.png)

**Comment by BadDogSkyrim** [comment]
Yeah, FO76 isn't supported at this point.
